site_name: SSOL DOCS
dev_addr: '0.0.0.0:8000'
theme: 
    name: material
    language: 'pt'
    palette:
        primary: 'white'
    # logo: 'favicon.png'

repo_name: 'SSOL'
repo_url: 'https://github.com/fga-projeto-integrador-1/SSol'

extra_css:   
    - 'stylesheets/cards.css'

plugins:
    - search
    - awesome-pages
